# Generated by Django 2.1.3 on 2018-11-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='num3',
            new_name='add',
        ),
    ]
