# Generated by Django 2.1.3 on 2018-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0002_auto_20181127_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='add',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
